# Generated by Django 5.0.2 on 2024-03-13 01:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fund",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255)),
                ("Budget", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Rest", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "db_table": "Fund",
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255)),
                ("Date", models.DateField()),
                (
                    "Category",
                    models.IntegerField(
                        choices=[
                            (0, "Grocery"),
                            (1, "Entertainment"),
                            (2, "Transportation"),
                            (3, "Housing"),
                            (4, "Medical"),
                            (5, "Education"),
                            (6, "Investment"),
                            (7, "Other"),
                        ]
                    ),
                ),
                ("description", models.TextField()),
                ("type", models.IntegerField(choices=[(0, "In"), (1, "Out")])),
                (
                    "Amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
            ],
            options={
                "db_table": "Record",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("report_detail", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "Report",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "User",
            },
        ),
    ]
